[2025-03-14 17:41:48][INFO] Loaded utilities from vitai_scripts package
[2025-03-14 17:41:48][INFO] Loaded 128 patients total from PatientFeatures.csv.
[2025-03-14 17:41:48][DEBUG] Data columns: ['Id', 'AGE', 'DECEASED', 'GENDER', 'RACE', 'ETHNICITY', 'MARITAL', 'HEALTHCARE_EXPENSES', 'HEALTHCARE_COVERAGE', 'INCOME', 'Hospitalizations_Count', 'Medications_Count', 'Abnormal_Observations_Count']
[2025-03-14 17:41:48][DEBUG] Data sample:
                                     Id  ...  Abnormal_Observations_Count
0  d22baeed-9be0-de63-b594-7327d92c79d8  ...                            0
1  d5b7517f-b1d9-3953-f576-79f3ec822708  ...                            0
2  76f70739-2e73-e09d-fa04-360a0f608912  ...                            0
3  368adb6b-616b-289e-6d4e-8c224c089ce8  ...                            0
4  646515fd-3c1e-ea90-fb0e-a458c276cce9  ...                            0

[5 rows x 13 columns]
[2025-03-14 17:41:48][INFO] Loaded 66 diabetic patients from file
[2025-03-14 17:41:48][INFO] Patient groups => Diabetes=66, CKD=0, None=62
[2025-03-14 17:41:48][INFO] Running model 'combined_diabetes_tabnet' for group 'diabetes' with 66 patients.
[2025-03-14 17:41:48][DEBUG] Group 'diabetes' DataFrame columns: ['Id', 'AGE', 'DECEASED', 'GENDER', 'RACE', 'ETHNICITY', 'MARITAL', 'HEALTHCARE_EXPENSES', 'HEALTHCARE_COVERAGE', 'INCOME', 'Hospitalizations_Count', 'Medications_Count', 'Abnormal_Observations_Count']
[2025-03-14 17:41:48][DEBUG] Group 'diabetes' DataFrame sample:
                                     Id  ...  Abnormal_Observations_Count
0  d22baeed-9be0-de63-b594-7327d92c79d8  ...                            0
1  d5b7517f-b1d9-3953-f576-79f3ec822708  ...                            0
2  76f70739-2e73-e09d-fa04-360a0f608912  ...                            0

[3 rows x 13 columns]
[2025-03-14 17:41:48][INFO] Found model at: C:\Users\imran\Documents\VITAI\Data\finals\combined_diabetes_tabnet\combined_diabetes_tabnet_model.zip
[2025-03-14 17:41:48][INFO] Loading model combined_diabetes_tabnet on device: cpu
C:\Users\imran\miniconda3\envs\tf_gpu_env\lib\site-packages\pytorch_tabnet\abstract_model.py:82: UserWarning: Device used : cpu
  warnings.warn(f"Device used : {self.device}")
C:\Users\imran\miniconda3\envs\tf_gpu_env\lib\site-packages\pytorch_tabnet\abstract_model.py:454: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  saved_state_dict = torch.load(f, map_location=self.device)
[2025-03-14 17:41:48][INFO] Loaded scaler from C:\Users\imran\Documents\VITAI\Data\finals\combined_diabetes_tabnet\combined_diabetes_tabnet_scaler.joblib
[2025-03-14 17:41:48][DEBUG] [combined_diabetes_tabnet] Preprocessing 66 rows with columns: ['Id', 'AGE', 'DECEASED', 'GENDER', 'RACE', 'ETHNICITY', 'MARITAL', 'HEALTHCARE_EXPENSES', 'HEALTHCARE_COVERAGE', 'INCOME', 'Hospitalizations_Count', 'Medications_Count', 'Abnormal_Observations_Count']
[2025-03-14 17:41:48][DEBUG] [combined_diabetes_tabnet] Sample data:
                                     Id  ...  Abnormal_Observations_Count
0  d22baeed-9be0-de63-b594-7327d92c79d8  ...                            0
1  d5b7517f-b1d9-3953-f576-79f3ec822708  ...                            0
2  76f70739-2e73-e09d-fa04-360a0f608912  ...                            0

[3 rows x 13 columns]
[2025-03-14 17:41:48][DEBUG] [combined_diabetes_tabnet] Numeric feature_cols: ['AGE', 'DECEASED', 'GENDER', 'RACE', 'ETHNICITY', 'MARITAL', 'HEALTHCARE_EXPENSES', 'HEALTHCARE_COVERAGE', 'INCOME', 'Hospitalizations_Count', 'Medications_Count', 'Abnormal_Observations_Count']
[2025-03-14 17:41:48][DEBUG] [combined_diabetes_tabnet] Final shape of X: (66, 12)
[2025-03-14 17:41:48][INFO] Preprocessed features shape: (66, 12) for 66 patients
[2025-03-14 17:41:48][DEBUG] Sample raw features (first row): [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[2025-03-14 17:41:48][INFO] Applying scaler to features for model: combined_diabetes_tabnet
C:\Users\imran\miniconda3\envs\tf_gpu_env\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
[2025-03-14 17:41:48][ERROR] Error preprocessing features: X has 12 features, but StandardScaler is expecting 7 features as input.
[2025-03-14 17:41:48][ERROR] Traceback (most recent call last):
  File "C:\Users\imran\Documents\VITAI\run_patient_group_predictions.py", line 276, in run_model_for_group
    X = scaler.transform(X)
  File "C:\Users\imran\miniconda3\envs\tf_gpu_env\lib\site-packages\sklearn\utils\_set_output.py", line 316, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "C:\Users\imran\miniconda3\envs\tf_gpu_env\lib\site-packages\sklearn\preprocessing\_data.py", line 1045, in transform
    X = self._validate_data(
  File "C:\Users\imran\miniconda3\envs\tf_gpu_env\lib\site-packages\sklearn\base.py", line 654, in _validate_data
    self._check_n_features(X, reset=reset)
  File "C:\Users\imran\miniconda3\envs\tf_gpu_env\lib\site-packages\sklearn\base.py", line 443, in _check_n_features
    raise ValueError(
ValueError: X has 12 features, but StandardScaler is expecting 7 features as input.

[2025-03-14 17:41:48][ERROR] Failed to get predictions for model 'combined_diabetes_tabnet'
[2025-03-14 17:41:48][INFO] No patients in 'ckd' group. Skipping combined_all_ckd_tabnet.
[2025-03-14 17:41:48][INFO] Running model 'combined_none_tabnet' for group 'none' with 62 patients.
[2025-03-14 17:41:48][DEBUG] Group 'none' DataFrame columns: ['Id', 'AGE', 'DECEASED', 'GENDER', 'RACE', 'ETHNICITY', 'MARITAL', 'HEALTHCARE_EXPENSES', 'HEALTHCARE_COVERAGE', 'INCOME', 'Hospitalizations_Count', 'Medications_Count', 'Abnormal_Observations_Count']
[2025-03-14 17:41:48][DEBUG] Group 'none' DataFrame sample:
                                      Id  ...  Abnormal_Observations_Count
66  a22ea4c2-f331-76cc-3496-5e72f6ede274  ...                            0
67  46d47773-bd4e-a28e-5fcf-31cf9cfc65a3  ...                            0
68  90215cfc-25ce-3147-61cd-fa4a974f9c09  ...                            0

[3 rows x 13 columns]
[2025-03-14 17:41:48][INFO] Found model at: C:\Users\imran\Documents\VITAI\Data\finals\combined_none_tabnet\combined_none_tabnet_model.zip
[2025-03-14 17:41:48][INFO] Loading model combined_none_tabnet on device: cpu
C:\Users\imran\miniconda3\envs\tf_gpu_env\lib\site-packages\pytorch_tabnet\abstract_model.py:82: UserWarning: Device used : cpu
  warnings.warn(f"Device used : {self.device}")
C:\Users\imran\miniconda3\envs\tf_gpu_env\lib\site-packages\pytorch_tabnet\abstract_model.py:454: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  saved_state_dict = torch.load(f, map_location=self.device)
[2025-03-14 17:41:48][INFO] Loaded scaler from C:\Users\imran\Documents\VITAI\Data\finals\combined_none_tabnet\combined_none_tabnet_scaler.joblib
[2025-03-14 17:41:48][DEBUG] [combined_none_tabnet] Preprocessing 62 rows with columns: ['Id', 'AGE', 'DECEASED', 'GENDER', 'RACE', 'ETHNICITY', 'MARITAL', 'HEALTHCARE_EXPENSES', 'HEALTHCARE_COVERAGE', 'INCOME', 'Hospitalizations_Count', 'Medications_Count', 'Abnormal_Observations_Count']
[2025-03-14 17:41:48][DEBUG] [combined_none_tabnet] Sample data:
                                      Id  ...  Abnormal_Observations_Count
66  a22ea4c2-f331-76cc-3496-5e72f6ede274  ...                            0
67  46d47773-bd4e-a28e-5fcf-31cf9cfc65a3  ...                            0
68  90215cfc-25ce-3147-61cd-fa4a974f9c09  ...                            0

[3 rows x 13 columns]
[2025-03-14 17:41:48][DEBUG] [combined_none_tabnet] Numeric feature_cols: ['AGE', 'DECEASED', 'GENDER', 'RACE', 'ETHNICITY', 'MARITAL', 'HEALTHCARE_EXPENSES', 'HEALTHCARE_COVERAGE', 'INCOME', 'Hospitalizations_Count', 'Medications_Count', 'Abnormal_Observations_Count']
[2025-03-14 17:41:48][DEBUG] [combined_none_tabnet] Final shape of X: (62, 12)
[2025-03-14 17:41:48][INFO] Preprocessed features shape: (62, 12) for 62 patients
[2025-03-14 17:41:48][DEBUG] Sample raw features (first row): [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[2025-03-14 17:41:48][INFO] Applying scaler to features for model: combined_none_tabnet
C:\Users\imran\miniconda3\envs\tf_gpu_env\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
[2025-03-14 17:41:48][ERROR] Error preprocessing features: X has 12 features, but StandardScaler is expecting 7 features as input.
[2025-03-14 17:41:48][ERROR] Traceback (most recent call last):
  File "C:\Users\imran\Documents\VITAI\run_patient_group_predictions.py", line 276, in run_model_for_group
    X = scaler.transform(X)
  File "C:\Users\imran\miniconda3\envs\tf_gpu_env\lib\site-packages\sklearn\utils\_set_output.py", line 316, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "C:\Users\imran\miniconda3\envs\tf_gpu_env\lib\site-packages\sklearn\preprocessing\_data.py", line 1045, in transform
    X = self._validate_data(
  File "C:\Users\imran\miniconda3\envs\tf_gpu_env\lib\site-packages\sklearn\base.py", line 654, in _validate_data
    self._check_n_features(X, reset=reset)
  File "C:\Users\imran\miniconda3\envs\tf_gpu_env\lib\site-packages\sklearn\base.py", line 443, in _check_n_features
    raise ValueError(
ValueError: X has 12 features, but StandardScaler is expecting 7 features as input.

[2025-03-14 17:41:48][ERROR] Failed to get predictions for model 'combined_none_tabnet'
[2025-03-14 17:41:48][ERROR] Multi-model inference completed with errors.
